/// Generates an entity initializer and an in-place `update` method from one
/// initializer declaration.
///
/// Statements outside the marker macros are emitted into both declarations in
/// their original order. Use ``onInit(_:)`` for initialization-only work, such
/// as assigning immutable identity, and ``onUpdate(_:)`` for updates
/// that are meaningful only after an entity already exists.
///
/// ```swift
/// @InitAndUpdate
/// init(id: ID, title: String) {
///   #onInit {
///     self.id = id
///   }
///   self.title = title
/// }
/// ```
///
/// The expansion above creates `mutating func update(id:title:)` for a struct
/// and `func update(id:title:)` for a class. The generated method has the same
/// access level, parameters, effects, generic parameters, and generic
/// constraints as the initializer. For example, `init(with json: JSON)`
/// generates `update(with: json:)` without making this macro depend on JSON.
///
/// This macro supports designated initializers declared directly in a class or
/// struct. Failable initializers and initializer-specific modifiers or
/// attributes are diagnosed because they cannot be represented faithfully by a
/// regular `update` method.
@attached(body)
@attached(peer, names: named(update))
public macro InitAndUpdate() = #externalMacro(
  module: "StateGraphNormalizationMacro",
  type: "InitAndUpdateMacro"
)

/// Marks statements that are emitted only into an ``InitAndUpdate`` initializer.
///
/// Use this for work required to establish an instance's invariant, especially
/// assignments to immutable stored properties. The marker is valid only as a
/// direct statement in an initializer annotated with ``InitAndUpdate``.
@freestanding(expression)
public macro onInit(_ body: () -> Void) -> Void = #externalMacro(
  module: "StateGraphNormalizationMacro",
  type: "OnInitMarkerMacro"
)

/// Marks statements that are emitted only into the `update` method generated by
/// ``InitAndUpdate``.
///
/// The marker is valid only as a direct statement in an initializer annotated
/// with ``InitAndUpdate``.
@freestanding(expression)
public macro onUpdate(_ body: () -> Void) -> Void = #externalMacro(
  module: "StateGraphNormalizationMacro",
  type: "OnUpdateMarkerMacro"
)
